Testing out new install version

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,9 +2,31 @@
 # Nicholas Mahdavi
 # nickmahda@gmail.com
 
+if [ $(id -u) -ne 0 ]; then
+    echo "To install many of the packages, superuser is required."
+    echo "The packages include: brew/apt packages, various zsh prompts, and more."
+    read -rp "Do you want to continue? [y/N]" response
+    if [[ "$response" =~ ^([yY][eE][sS|[yY])+$ ]]; then
+        no_root=1
+    else
+        exit 1
+fi
+
+while [ -z "$multi" ]; do
+    read -rp "Do multiple users use this computer? (y/N/q)" response
+    case "$response" in
+       [yY][eE][sS]|[yY]) multi=1 ;;
+       [nN][oO]|[nN]) multi=0 ;;
+       [qQ][uU][iI][tT]|[qQ]) exit 0 ;;
+       *) echo "Please enter a valid response." ;;
+    esac
+done
+
+usrname=$(who am i)
+
 cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
 
-DIR=`pwd`
+DIR=$(pwd)
 
 git submodule init && git submodule update
 
@@ -18,11 +40,18 @@ done
 ln -sfv "$DIR/zsh" ~/.zsh
 
 if [[ "$OSTYPE" == "darwin"* ]]; then
-    [ -z "$(which brew)" ] && ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+    if [ -z "$(which brew)" ] && ((no_root)); then
+       su - $usrname -c 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
 
-    brew install cmake coreutils emacs gcc gnu-chess htop nano nginx opencv pkg-config python tmux tree vim zsh zsh-history-substring-search
-    brew cask install google-chrome discord eqmac firefox gimp inkscape java opera-neon osxfuse spotify xquartz virtualbox
+    if su - $usrname -c "test -w /usr/local/"; then
+        ((multi)) && { chmod g+w /usr/local; chgrp staff /usr/local } || chown -R $usrname $(su - $usrname -c 'brew --prefix')/*
 
+    su - $usrname -c 'brew install cmake coreutils emacs gcc gnu-chess htop nano nginx opencv pkg-config python tmux tree vim zsh'
+    su - $usrname -c 'brew cask install google-chrome discord eqmac firefox gimp inkscape java opera-neon osxfuse spotify xquartz virtualbox'
+
+elif [[ "$OSTYPE" == "linux"* ]]; then
+    apt install emacs gnuchess htop pkg-config python3-dev tmux zsh
+    echo "You may have to compile vim from scratch to work with this .vimrc."
 fi
 
 cd zsh
@@ -45,7 +74,6 @@ for f in .tmux*; do
 done
 
 ln -sfv ./Blex Mono Nerd Font Complete.ttf ~/Library/Fonts/
-
 
 echo "Moving to vim install"
 
